name: "💡 [FR] Suggestion d'idée / Nouvelle fonctionnalité"
description: "Envie de soumettre une nouvelle idée, amélioration ou une nouvelle fonctionnalité."
title: "💡 Titre de mon idée"
labels: ["lang:fr", "💡 idea"]
type: feature
body:
  - type: markdown
    attributes:
      value: |
        <br/>

        **Merci pour votre proposition !**
        Avant de commencer, merci de prendre le temps de partager votre idée avec nous ! Pour éviter les doublons, pensez à vérifier au préalable dans les tickets existants ou sur notre **roadmap** (si elle est disponible) que le sujet n'est pas déjà en cours d'étude. Si c'est le cas, n'hésitez pas à rejoindre la conversation directement sur le ticket concerné !
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Veuillez fournir une description détaillée de votre idée en 2-3 phrases. Ne décrivez pas encore les bénéfices, concentrez-vous uniquement sur la fonctionnalité et son comportement.
    validations:
      required: true
      
  - type: textarea
    id: use-cases
    attributes:
      label: Cas d'usage / Récit utilisateur
      description: |
        Expliquez comment votre idée fonctionnera du point de vue de l'utilisateur. En quoi ce changement va-t-il apporter de la valeur au projet et à la communauté ?
        
        **Structure recommandée pour votre User Story:**
        - **En tant que**, [profil utilisateur]
        - **Je souhaite**, [la fonctionnalité/l'action]
        - **Afin de**, [le bénéfice ou la valeur ajoutée]
      placeholder: |
        - **En tant que**, ...
        - **Je souhaite**, ...
        - **Afin de**, ...
    validations:
      required: true

  - type: upload
    id: visuals
    attributes:
      label: 📊 Visuels (Optionnel)
      description: "Glissez-deposez vos fichiers, captures d'écran ou maquettes pour illustrer votre idée."

  - type: checkboxes
    id: checklist
    attributes:
      label: Avant de soumettre
      description: Veuillez vous assurer que votre proposition respecte les points suivants.
      options:
        - label: "J'ai vérifié que mon idée n'a pas déjà été proposée."
          required: true
        - label: "Je confirme que mon idée est bien une demande d'évolution et non un rapport de bug."
          required: true