name: "💡 [FR] Suggestion d'idée"
description: "Envie de soumettre une idée, une amélioration ou une nouvelle fonctionnalité."
title: "[💡 IDÉE] "
labels: ["lang:fr", "💡 idée"]
body:
  - type: markdown
    attributes:
      value: |
        ### Avant de commencer
        Merci de prendre le temps de proposer une idée ! Vérifiez d'abord dans les tickets existants ou notre roadmap si votre idée n'est pas déjà en cours d'étude.

  - type: textarea
    id: description
    attributes:
      label: 🚀 Description de l'idée
      description: |
        Veuillez fournir une description détaillée de votre idée en 2-3 phrases. Ne décrivez pas encore les bénéfices, concentrez-vous uniquement sur la fonctionnalité et son comportement.
    validations:
      required: true
      
  - type: textarea
    id: use-cases
    attributes:
      label: 👥 Cas d'usage / Récit utilisateur
      description: |
        Expliquez comment votre idée fonctionnera du point de vue de l'utilisateur. En quoi ce changement va-t-il apporter de la valeur au projet et à la communauté ?
        
        **Structure recommandée pour votre User Story:**
        - **En tant que** [profil utilisateur]
        - **Je souhaite** [la fonctionnalité/l'action]
        - **Afin de** [le bénéfice ou la valeur ajoutée]
      placeholder: |
        En tant que...
        Je souhaite...
        Afin de...
    validations:
      required: true

  - type: upload
    id: visuals
    attributes:
      label: 📊 Visuels (Optionnel)
      description: "Glissez-deposez vos fichiers, captures d'écran ou maquettes pour illustrer votre idée."

  - type: checkboxes
    id: checklist
    attributes:
      label: Avant de soumettre
      description: Veuillez vous assurer que votre proposition respecte les points suivants.
      options:
        - label: "J'ai vérifié que mon idée n'a pas déjà été proposée."
          required: true
        - label: "Je confirme que mon idée est bien une demande d'évolution et non un rapport de bug."
          required: true