name: Sync Labels Globally

on:
  push:
    branches: [main]
    paths:
      - '.github/labels.yml'
  workflow_dispatch: # Allow manual launch

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      # Listing of repo's organization to iterate sync
      matrix:
        repo:
          - AOT-DEP-BADI/grist-custom-widget-markdown-dsfr
          - AOT-DEP-BADI/grist-custom-widget-vite

    steps:
      - name: Checkout Configuration
        uses: actions/checkout@v4

      - name: Sync Labels to ${{ matrix.repo }}
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
          # Set to false to delete old labels
          skip-delete: true
          github-token: ${{ secrets.SYNC_LABELS_TOKEN }}
        env:
          GITHUB_REPOSITORY: ${{ matrix.repo }}