name: Global Labels Synchronization

on:
  push:
    branches: [main]
    paths:
      - '.github/labels.yml'
  workflow_dispatch: # Allow manual launch

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      # Listing of repo's organization to iterate sync
      matrix:
        repo:
          - AOT-DEP-BADI/grist-custom-widget-markdown-dsfr
          - AOT-DEP-BADI/grist-custom-widget-vite

    steps:
      - name: Checkout Configuration
        uses: actions/checkout@v7
        
      - name: Sync Labels to ${{ matrix.repo }}
        run: |
          # Fetch and delete all existing labels from the target repository
          echo "🧹 Cleaning up old labels on ${{ matrix.repo }}..."
          gh label list --repo ${{ matrix.repo }} --json name --jq '.[].name' | while read -r label_name; do
            gh label delete "$label_name" --repo ${{ matrix.repo }} --yes
          done

          # Clone the single source of truth (.github) into the target repository
          echo "🚀 Injecting single source of truth labels.yml on ${{ matrix.repo }}..."
          gh label import --repo ${{ matrix.repo }} .github/labels.yml
        env:
          GH_TOKEN: ${{ secrets.SYNC_LABELS_TOKEN }}